// <auto-generated />
namespace WebServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FK_for_FBS_VersuchSechs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FK_for_FBS_VersuchSechs));
        
        string IMigrationMetadata.Id
        {
            get { return "201512292116316_FK_for_FBS_VersuchSechs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
