// <auto-generated />
namespace WebServer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FK_in_FBS_eingefuegt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FK_in_FBS_eingefuegt));
        
        string IMigrationMetadata.Id
        {
            get { return "201601031048110_FK_in_FBS_eingefuegt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
